const mockProducts = [
  {
    id: 1,
    name: 'Vestido Floral Elegante',
    description: 'Vestido leve de verão com estampa floral.',
    price: 189.9,
    image: 'https://i.imgur.com/Qp13a3x.png',
  },
  {
    id: 2,
    name: 'Calça Jeans Skinny',
    description: 'Calça jeans de alta qualidade e conforto.',
    price: 229.9,
    image: 'https://i.imgur.com/sC03i4g.png',
  },
  {
    id: 3,
    name: 'Blusa de Seda Pura',
    description: 'Blusa elegante para ocasiões especiais.',
    price: 349.9,
    image: 'https://i.imgur.com/e2imHAP.png',
  },
  {
    id: 4,
    name: 'Saia Midi Plissada',
    description: 'Saia versátil para looks casuais e formais.',
    price: 159.9,
    image: 'https://i.imgur.com/e2imHAP.png',
  },
  {
    id: 5,
    name: 'Jaqueta de Couro Sintético',
    description: 'Jaqueta moderna para um look arrojado.',
    price: 399.9,
    image: 'https://i.imgur.com/sC03i4g.png',
  },
  {
    id: 6,
    name: 'Camiseta Básica de Algodão',
    description: 'Conforto e simplicidade para o dia a dia.',
    price: 79.9,
    image: 'https://i.imgur.com/Qp13a3x.png',
  },
  {
    id: 7,
    name: 'Macacão Pantalona',
    description: 'Elegância e conforto em uma única peça.',
    price: 299.9,
    image: 'https://i.imgur.com/e2imHAP.png',
  },
  {
    id: 8,
    name: 'Short de Linho',
    description: 'Perfeito para os dias quentes de verão.',
    price: 129.9,
    image: 'https://i.imgur.com/sC03i4g.png',
  },
  {
    id: 9,
    name: 'Blazer Acinturado',
    description: 'Um toque de sofisticação para o seu look de trabalho.',
    price: 319.9,
    image: 'https://i.imgur.com/Qp13a3x.png',
  },
  {
    id: 10,
    name: 'Vestido de Festa Longo',
    description: 'Brilhe em eventos noturnos com este modelo.',
    price: 499.9,
    image: 'https://i.imgur.com/e2imHAP.png',
  },
  {
    id: 11,
    name: 'Cardigan de Lã',
    description: 'Aconchegante e estiloso para o inverno.',
    price: 199.9,
    image: 'https://i.imgur.com/sC03i4g.png',
  },
  {
    id: 12,
    name: 'Calça de Alfaiataria',
    description: 'Elegância e corte impecável para o escritório.',
    price: 259.9,
    image: 'https://i.imgur.com/Qp13a3x.png',
  },
  {
    id: 13,
    name: 'Regata de Viscose',
    description: 'Leveza e frescor para compor diversos looks.',
    price: 89.9,
    image: 'https://i.imgur.com/e2imHAP.png',
  },
  {
    id: 14,
    name: 'Moletom com Capuz',
    description: 'Conforto e estilo para os momentos de lazer.',
    price: 179.9,
    image: 'https://i.imgur.com/sC03i4g.png',
  },
  {
    id: 15,
    name: 'Bermuda Ciclista',
    description: 'Tendência e conforto para atividades físicas.',
    price: 99.9,
    image: 'https://i.imgur.com/Qp13a3x.png',
  },
  {
    id: 16,
    name: 'Top Cropped Canelado',
    description: 'Moderno e versátil para o dia a dia.',
    price: 69.9,
    image: 'https://i.imgur.com/e2imHAP.png',
  },
]

export { mockProducts }
